# Generated by Django 4.0.5 on 2022-06-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectors',
            field=models.ManyToManyField(to='base_app.lector'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='base_app.student'),
        ),
        migrations.AddField(
            model_name='lector',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lector',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
